// <copyright file="NewsTickerForm.cs" company="SteemSoftware">
//     CC0 1.0 Universal (CC0 1.0) - Public Domain Dedication
//     https://creativecommons.org/publicdomain/zero/1.0/legalcode
// </copyright>
// <auto-generated />
namespace SteemSoftware
{
    partial class NewsTickerForm
    {
        /// <summary>
        /// Designer variable used to keep track of non-visual components.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Disposes resources used by the form.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (components != null)
                {
                    components.Dispose();
                }
            }
            base.Dispose(disposing);
        }

        /// <summary>
        /// This method is required for Windows Forms designer support.
        /// Do not change the method contents inside the source code editor. The Forms designer might
        /// not be able to load this method if it was changed manually.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.newsTickerTimer = new System.Windows.Forms.Timer(this.components);
            this.SuspendLayout();
            // 
            // newsTickerTimer
            // 
            this.newsTickerTimer.Interval = 20;
            this.newsTickerTimer.Tick += new System.EventHandler(this.NewsTickerTimerTick);
            // 
            // NewsTickerForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(10, 10);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "NewsTickerForm";
            this.ShowInTaskbar = false;
            this.Text = "To-do List News Ticker";
            this.Shown += new System.EventHandler(this.OnNewsTickerFormShown);
            this.ResumeLayout(false);
        }
        private System.Windows.Forms.Timer newsTickerTimer;
    }
}
