// <copyright file="YouTubeMultiPlaylistAggregatorForm.Designer.cs" company="SteemSoftware">
//     CC0 1.0 Universal (CC0 1.0) - Public Domain Dedication
//     https://creativecommons.org/publicdomain/zero/1.0/legalcode
// </copyright>
// <auto-generated />
namespace SteemSoftware
{
    partial class YouTubeMultiPlaylistAggregatorForm
    {
        /// <summary>
        /// Designer variable used to keep track of non-visual components.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Disposes resources used by the form.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (components != null)
                {
                    components.Dispose();
                }
            }
            base.Dispose(disposing);
        }

        /// <summary>
        /// This method is required for Windows Forms designer support.
        /// Do not change the method contents inside the source code editor. The Forms designer might
        /// not be able to load this method if it was changed manually.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(YouTubeMultiPlaylistAggregatorForm));
            this.saveFileDialog = new System.Windows.Forms.SaveFileDialog();
            this.mainMenuStrip = new System.Windows.Forms.MenuStrip();
            this.fileToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.newToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripSeparator2 = new System.Windows.Forms.ToolStripSeparator();
            this.exitToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.editToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.cutToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.copyToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.pasteToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripSeparator4 = new System.Windows.Forms.ToolStripSeparator();
            this.selectAllToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.optionsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.addedVideosToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.alternatefirstToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.alternatelastToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.addedlistsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.fetchAllToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.videosToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.videosToolStripMenuItem1 = new System.Windows.Forms.ToolStripMenuItem();
            this.videosToolStripMenuItem2 = new System.Windows.Forms.ToolStripMenuItem();
            this.videosToolStripMenuItem3 = new System.Windows.Forms.ToolStripMenuItem();
            this.videosToolStripMenuItem4 = new System.Windows.Forms.ToolStripMenuItem();
            this.videosToolStripMenuItem5 = new System.Windows.Forms.ToolStripMenuItem();
            this.customValueToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.helpToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.aboutToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.mainStatusStrip = new System.Windows.Forms.StatusStrip();
            this.progressToolStripProgressBar = new System.Windows.Forms.ToolStripProgressBar();
            this.statusToolStripStatusLabel = new System.Windows.Forms.ToolStripStatusLabel();
            this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.tableLayoutPanel2 = new System.Windows.Forms.TableLayoutPanel();
            this.addLabel = new System.Windows.Forms.Label();
            this.listTextBox = new System.Windows.Forms.TextBox();
            this.alternatingButton = new System.Windows.Forms.Button();
            this.sequentialButton = new System.Windows.Forms.Button();
            this.shuffledButton = new System.Windows.Forms.Button();
            this.tableLayoutPanel3 = new System.Windows.Forms.TableLayoutPanel();
            this.playListView = new System.Windows.Forms.ListView();
            this.titleColumnHeader = new System.Windows.Forms.ColumnHeader();
            this.authorColumnHeader = new System.Windows.Forms.ColumnHeader();
            this.tableLayoutPanel4 = new System.Windows.Forms.TableLayoutPanel();
            this.plsButton = new System.Windows.Forms.Button();
            this.m3uButton = new System.Windows.Forms.Button();
            this.tableLayoutPanel5 = new System.Windows.Forms.TableLayoutPanel();
            this.videoRadioButton = new System.Windows.Forms.RadioButton();
            this.audioRadioButton = new System.Windows.Forms.RadioButton();
            this.mainMenuStrip.SuspendLayout();
            this.mainStatusStrip.SuspendLayout();
            this.tableLayoutPanel1.SuspendLayout();
            this.tableLayoutPanel2.SuspendLayout();
            this.tableLayoutPanel3.SuspendLayout();
            this.tableLayoutPanel4.SuspendLayout();
            this.tableLayoutPanel5.SuspendLayout();
            this.SuspendLayout();
            // 
            // saveFileDialog
            // 
            this.saveFileDialog.DefaultExt = "txt";
            this.saveFileDialog.Filter = "Text Files (*.txt)|*.txt|All files (*.*)|*.*";
            this.saveFileDialog.Title = "Save playlist";
            // 
            // mainMenuStrip
            // 
            this.mainMenuStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
                                    this.fileToolStripMenuItem,
                                    this.editToolStripMenuItem,
                                    this.optionsToolStripMenuItem,
                                    this.helpToolStripMenuItem});
            this.mainMenuStrip.Location = new System.Drawing.Point(0, 0);
            this.mainMenuStrip.Name = "mainMenuStrip";
            this.mainMenuStrip.Size = new System.Drawing.Size(324, 24);
            this.mainMenuStrip.TabIndex = 2;
            // 
            // fileToolStripMenuItem
            // 
            this.fileToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
                                    this.newToolStripMenuItem,
                                    this.toolStripSeparator2,
                                    this.exitToolStripMenuItem});
            this.fileToolStripMenuItem.Name = "fileToolStripMenuItem";
            this.fileToolStripMenuItem.Size = new System.Drawing.Size(37, 20);
            this.fileToolStripMenuItem.Text = "&File";
            // 
            // newToolStripMenuItem
            // 
            this.newToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("newToolStripMenuItem.Image")));
            this.newToolStripMenuItem.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.newToolStripMenuItem.Name = "newToolStripMenuItem";
            this.newToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.N)));
            this.newToolStripMenuItem.Size = new System.Drawing.Size(141, 22);
            this.newToolStripMenuItem.Text = "&New";
            this.newToolStripMenuItem.Click += new System.EventHandler(this.OnNewToolStripMenuItemClick);
            // 
            // toolStripSeparator2
            // 
            this.toolStripSeparator2.Name = "toolStripSeparator2";
            this.toolStripSeparator2.Size = new System.Drawing.Size(138, 6);
            // 
            // exitToolStripMenuItem
            // 
            this.exitToolStripMenuItem.Name = "exitToolStripMenuItem";
            this.exitToolStripMenuItem.Size = new System.Drawing.Size(141, 22);
            this.exitToolStripMenuItem.Text = "E&xit";
            this.exitToolStripMenuItem.Click += new System.EventHandler(this.OnExitToolStripMenuItemClick);
            // 
            // editToolStripMenuItem
            // 
            this.editToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
                                    this.cutToolStripMenuItem,
                                    this.copyToolStripMenuItem,
                                    this.pasteToolStripMenuItem,
                                    this.toolStripSeparator4,
                                    this.selectAllToolStripMenuItem});
            this.editToolStripMenuItem.Name = "editToolStripMenuItem";
            this.editToolStripMenuItem.Size = new System.Drawing.Size(39, 20);
            this.editToolStripMenuItem.Text = "&Edit";
            // 
            // cutToolStripMenuItem
            // 
            this.cutToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("cutToolStripMenuItem.Image")));
            this.cutToolStripMenuItem.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.cutToolStripMenuItem.Name = "cutToolStripMenuItem";
            this.cutToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.X)));
            this.cutToolStripMenuItem.Size = new System.Drawing.Size(164, 22);
            this.cutToolStripMenuItem.Text = "Cu&t";
            this.cutToolStripMenuItem.Click += new System.EventHandler(this.OnCutToolStripMenuItemClick);
            // 
            // copyToolStripMenuItem
            // 
            this.copyToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("copyToolStripMenuItem.Image")));
            this.copyToolStripMenuItem.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.copyToolStripMenuItem.Name = "copyToolStripMenuItem";
            this.copyToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.C)));
            this.copyToolStripMenuItem.Size = new System.Drawing.Size(164, 22);
            this.copyToolStripMenuItem.Text = "&Copy";
            this.copyToolStripMenuItem.Click += new System.EventHandler(this.OnCopyToolStripMenuItemClick);
            // 
            // pasteToolStripMenuItem
            // 
            this.pasteToolStripMenuItem.Image = ((System.Drawing.Image)(resources.GetObject("pasteToolStripMenuItem.Image")));
            this.pasteToolStripMenuItem.ImageTransparentColor = System.Drawing.Color.Magenta;
            this.pasteToolStripMenuItem.Name = "pasteToolStripMenuItem";
            this.pasteToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.V)));
            this.pasteToolStripMenuItem.Size = new System.Drawing.Size(164, 22);
            this.pasteToolStripMenuItem.Text = "&Paste";
            this.pasteToolStripMenuItem.Click += new System.EventHandler(this.OnPasteToolStripMenuItemClick);
            // 
            // toolStripSeparator4
            // 
            this.toolStripSeparator4.Name = "toolStripSeparator4";
            this.toolStripSeparator4.Size = new System.Drawing.Size(161, 6);
            // 
            // selectAllToolStripMenuItem
            // 
            this.selectAllToolStripMenuItem.Name = "selectAllToolStripMenuItem";
            this.selectAllToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.A)));
            this.selectAllToolStripMenuItem.Size = new System.Drawing.Size(164, 22);
            this.selectAllToolStripMenuItem.Text = "Select &All";
            this.selectAllToolStripMenuItem.Click += new System.EventHandler(this.OnSelectAllToolStripMenuItemClick);
            // 
            // optionsToolStripMenuItem
            // 
            this.optionsToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
                                    this.addedVideosToolStripMenuItem,
                                    this.addedlistsToolStripMenuItem});
            this.optionsToolStripMenuItem.Name = "optionsToolStripMenuItem";
            this.optionsToolStripMenuItem.Size = new System.Drawing.Size(61, 20);
            this.optionsToolStripMenuItem.Text = "&Options";
            // 
            // addedVideosToolStripMenuItem
            // 
            this.addedVideosToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
                                    this.alternatefirstToolStripMenuItem,
                                    this.alternatelastToolStripMenuItem});
            this.addedVideosToolStripMenuItem.Name = "addedVideosToolStripMenuItem";
            this.addedVideosToolStripMenuItem.Size = new System.Drawing.Size(146, 22);
            this.addedVideosToolStripMenuItem.Text = "&Added videos";
            this.addedVideosToolStripMenuItem.DropDownItemClicked += new System.Windows.Forms.ToolStripItemClickedEventHandler(this.OnToolStripMenuItemDropDownItemClicked);
            // 
            // alternatefirstToolStripMenuItem
            // 
            this.alternatefirstToolStripMenuItem.Name = "alternatefirstToolStripMenuItem";
            this.alternatefirstToolStripMenuItem.Size = new System.Drawing.Size(145, 22);
            this.alternatefirstToolStripMenuItem.Text = "Alternate &first";
            // 
            // alternatelastToolStripMenuItem
            // 
            this.alternatelastToolStripMenuItem.Checked = true;
            this.alternatelastToolStripMenuItem.CheckState = System.Windows.Forms.CheckState.Checked;
            this.alternatelastToolStripMenuItem.Name = "alternatelastToolStripMenuItem";
            this.alternatelastToolStripMenuItem.Size = new System.Drawing.Size(145, 22);
            this.alternatelastToolStripMenuItem.Text = "Alternate &last";
            // 
            // addedlistsToolStripMenuItem
            // 
            this.addedlistsToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
                                    this.fetchAllToolStripMenuItem,
                                    this.videosToolStripMenuItem,
                                    this.videosToolStripMenuItem1,
                                    this.videosToolStripMenuItem2,
                                    this.videosToolStripMenuItem3,
                                    this.videosToolStripMenuItem4,
                                    this.videosToolStripMenuItem5,
                                    this.customValueToolStripMenuItem});
            this.addedlistsToolStripMenuItem.Name = "addedlistsToolStripMenuItem";
            this.addedlistsToolStripMenuItem.Size = new System.Drawing.Size(146, 22);
            this.addedlistsToolStripMenuItem.Text = "Added &lists";
            this.addedlistsToolStripMenuItem.DropDownItemClicked += new System.Windows.Forms.ToolStripItemClickedEventHandler(this.OnToolStripMenuItemDropDownItemClicked);
            // 
            // fetchAllToolStripMenuItem
            // 
            this.fetchAllToolStripMenuItem.Checked = true;
            this.fetchAllToolStripMenuItem.CheckState = System.Windows.Forms.CheckState.Checked;
            this.fetchAllToolStripMenuItem.Name = "fetchAllToolStripMenuItem";
            this.fetchAllToolStripMenuItem.Size = new System.Drawing.Size(147, 22);
            this.fetchAllToolStripMenuItem.Text = "&Fetch all";
            // 
            // videosToolStripMenuItem
            // 
            this.videosToolStripMenuItem.Name = "videosToolStripMenuItem";
            this.videosToolStripMenuItem.Size = new System.Drawing.Size(147, 22);
            this.videosToolStripMenuItem.Text = "10 videos";
            // 
            // videosToolStripMenuItem1
            // 
            this.videosToolStripMenuItem1.Name = "videosToolStripMenuItem1";
            this.videosToolStripMenuItem1.Size = new System.Drawing.Size(147, 22);
            this.videosToolStripMenuItem1.Text = "20 videos";
            // 
            // videosToolStripMenuItem2
            // 
            this.videosToolStripMenuItem2.Name = "videosToolStripMenuItem2";
            this.videosToolStripMenuItem2.Size = new System.Drawing.Size(147, 22);
            this.videosToolStripMenuItem2.Text = "30 videos";
            // 
            // videosToolStripMenuItem3
            // 
            this.videosToolStripMenuItem3.Name = "videosToolStripMenuItem3";
            this.videosToolStripMenuItem3.Size = new System.Drawing.Size(147, 22);
            this.videosToolStripMenuItem3.Text = "40 videos";
            // 
            // videosToolStripMenuItem4
            // 
            this.videosToolStripMenuItem4.Name = "videosToolStripMenuItem4";
            this.videosToolStripMenuItem4.Size = new System.Drawing.Size(147, 22);
            this.videosToolStripMenuItem4.Text = "50 videos";
            // 
            // videosToolStripMenuItem5
            // 
            this.videosToolStripMenuItem5.Name = "videosToolStripMenuItem5";
            this.videosToolStripMenuItem5.Size = new System.Drawing.Size(147, 22);
            this.videosToolStripMenuItem5.Text = "100 videos";
            // 
            // customValueToolStripMenuItem
            // 
            this.customValueToolStripMenuItem.Name = "customValueToolStripMenuItem";
            this.customValueToolStripMenuItem.Size = new System.Drawing.Size(147, 22);
            this.customValueToolStripMenuItem.Text = "&Custom value";
            // 
            // helpToolStripMenuItem
            // 
            this.helpToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
                                    this.aboutToolStripMenuItem});
            this.helpToolStripMenuItem.Name = "helpToolStripMenuItem";
            this.helpToolStripMenuItem.Size = new System.Drawing.Size(44, 20);
            this.helpToolStripMenuItem.Text = "&Help";
            // 
            // aboutToolStripMenuItem
            // 
            this.aboutToolStripMenuItem.Name = "aboutToolStripMenuItem";
            this.aboutToolStripMenuItem.Size = new System.Drawing.Size(116, 22);
            this.aboutToolStripMenuItem.Text = "&About...";
            this.aboutToolStripMenuItem.Click += new System.EventHandler(this.OnAboutToolStripMenuItemClick);
            // 
            // mainStatusStrip
            // 
            this.mainStatusStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
                                    this.progressToolStripProgressBar,
                                    this.statusToolStripStatusLabel});
            this.mainStatusStrip.Location = new System.Drawing.Point(0, 340);
            this.mainStatusStrip.Name = "mainStatusStrip";
            this.mainStatusStrip.Size = new System.Drawing.Size(324, 22);
            this.mainStatusStrip.TabIndex = 3;
            this.mainStatusStrip.Text = "statusStrip1";
            // 
            // progressToolStripProgressBar
            // 
            this.progressToolStripProgressBar.Name = "progressToolStripProgressBar";
            this.progressToolStripProgressBar.Size = new System.Drawing.Size(100, 16);
            // 
            // statusToolStripStatusLabel
            // 
            this.statusToolStripStatusLabel.Name = "statusToolStripStatusLabel";
            this.statusToolStripStatusLabel.Size = new System.Drawing.Size(57, 17);
            this.statusToolStripStatusLabel.Text = "Waiting...";
            // 
            // tableLayoutPanel1
            // 
            this.tableLayoutPanel1.ColumnCount = 1;
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel1.Controls.Add(this.tableLayoutPanel2, 0, 0);
            this.tableLayoutPanel1.Controls.Add(this.tableLayoutPanel3, 0, 1);
            this.tableLayoutPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel1.Location = new System.Drawing.Point(0, 24);
            this.tableLayoutPanel1.Name = "tableLayoutPanel1";
            this.tableLayoutPanel1.RowCount = 2;
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel1.Size = new System.Drawing.Size(324, 316);
            this.tableLayoutPanel1.TabIndex = 4;
            // 
            // tableLayoutPanel2
            // 
            this.tableLayoutPanel2.ColumnCount = 3;
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.33333F));
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.33334F));
            this.tableLayoutPanel2.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.33334F));
            this.tableLayoutPanel2.Controls.Add(this.addLabel, 0, 0);
            this.tableLayoutPanel2.Controls.Add(this.listTextBox, 0, 1);
            this.tableLayoutPanel2.Controls.Add(this.alternatingButton, 1, 2);
            this.tableLayoutPanel2.Controls.Add(this.sequentialButton, 0, 2);
            this.tableLayoutPanel2.Controls.Add(this.shuffledButton, 2, 2);
            this.tableLayoutPanel2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel2.Location = new System.Drawing.Point(3, 3);
            this.tableLayoutPanel2.Name = "tableLayoutPanel2";
            this.tableLayoutPanel2.RowCount = 3;
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 25F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel2.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 35F));
            this.tableLayoutPanel2.Size = new System.Drawing.Size(318, 152);
            this.tableLayoutPanel2.TabIndex = 0;
            // 
            // addLabel
            // 
            this.tableLayoutPanel2.SetColumnSpan(this.addLabel, 3);
            this.addLabel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.addLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.addLabel.Location = new System.Drawing.Point(3, 0);
            this.addLabel.Name = "addLabel";
            this.addLabel.Size = new System.Drawing.Size(312, 25);
            this.addLabel.TabIndex = 1;
            this.addLabel.Text = "Add playlists / videos:";
            this.addLabel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // listTextBox
            // 
            this.tableLayoutPanel2.SetColumnSpan(this.listTextBox, 3);
            this.listTextBox.Dock = System.Windows.Forms.DockStyle.Fill;
            this.listTextBox.Location = new System.Drawing.Point(3, 28);
            this.listTextBox.Multiline = true;
            this.listTextBox.Name = "listTextBox";
            this.listTextBox.ScrollBars = System.Windows.Forms.ScrollBars.Both;
            this.listTextBox.Size = new System.Drawing.Size(312, 86);
            this.listTextBox.TabIndex = 0;
            this.listTextBox.WordWrap = false;
            // 
            // alternatingButton
            // 
            this.alternatingButton.Dock = System.Windows.Forms.DockStyle.Fill;
            this.alternatingButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.alternatingButton.Image = ((System.Drawing.Image)(resources.GetObject("alternatingButton.Image")));
            this.alternatingButton.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.alternatingButton.Location = new System.Drawing.Point(106, 118);
            this.alternatingButton.Margin = new System.Windows.Forms.Padding(1);
            this.alternatingButton.Name = "alternatingButton";
            this.alternatingButton.Size = new System.Drawing.Size(104, 33);
            this.alternatingButton.TabIndex = 2;
            this.alternatingButton.Text = "&Alternating";
            this.alternatingButton.UseVisualStyleBackColor = true;
            this.alternatingButton.Click += new System.EventHandler(this.OnAlternatingButtonClick);
            // 
            // sequentialButton
            // 
            this.sequentialButton.Dock = System.Windows.Forms.DockStyle.Fill;
            this.sequentialButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.sequentialButton.Image = ((System.Drawing.Image)(resources.GetObject("sequentialButton.Image")));
            this.sequentialButton.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.sequentialButton.Location = new System.Drawing.Point(1, 118);
            this.sequentialButton.Margin = new System.Windows.Forms.Padding(1);
            this.sequentialButton.Name = "sequentialButton";
            this.sequentialButton.Size = new System.Drawing.Size(103, 33);
            this.sequentialButton.TabIndex = 1;
            this.sequentialButton.Text = "&Sequential";
            this.sequentialButton.UseVisualStyleBackColor = true;
            this.sequentialButton.Click += new System.EventHandler(this.OnSequentialButtonClick);
            // 
            // shuffledButton
            // 
            this.shuffledButton.Dock = System.Windows.Forms.DockStyle.Fill;
            this.shuffledButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.shuffledButton.Image = ((System.Drawing.Image)(resources.GetObject("shuffledButton.Image")));
            this.shuffledButton.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.shuffledButton.Location = new System.Drawing.Point(212, 118);
            this.shuffledButton.Margin = new System.Windows.Forms.Padding(1);
            this.shuffledButton.Name = "shuffledButton";
            this.shuffledButton.Size = new System.Drawing.Size(105, 33);
            this.shuffledButton.TabIndex = 3;
            this.shuffledButton.Text = "S&huffled";
            this.shuffledButton.UseVisualStyleBackColor = true;
            this.shuffledButton.Click += new System.EventHandler(this.OnShuffledButtonClick);
            // 
            // tableLayoutPanel3
            // 
            this.tableLayoutPanel3.ColumnCount = 1;
            this.tableLayoutPanel3.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel3.Controls.Add(this.playListView, 0, 1);
            this.tableLayoutPanel3.Controls.Add(this.tableLayoutPanel4, 0, 2);
            this.tableLayoutPanel3.Controls.Add(this.tableLayoutPanel5, 0, 0);
            this.tableLayoutPanel3.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel3.Location = new System.Drawing.Point(3, 161);
            this.tableLayoutPanel3.Name = "tableLayoutPanel3";
            this.tableLayoutPanel3.RowCount = 3;
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 25F));
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel3.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 35F));
            this.tableLayoutPanel3.Size = new System.Drawing.Size(318, 152);
            this.tableLayoutPanel3.TabIndex = 1;
            // 
            // playListView
            // 
            this.playListView.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] {
                                    this.titleColumnHeader,
                                    this.authorColumnHeader});
            this.playListView.Dock = System.Windows.Forms.DockStyle.Fill;
            this.playListView.FullRowSelect = true;
            this.playListView.Location = new System.Drawing.Point(3, 28);
            this.playListView.MultiSelect = false;
            this.playListView.Name = "playListView";
            this.playListView.Size = new System.Drawing.Size(312, 86);
            this.playListView.TabIndex = 4;
            this.playListView.UseCompatibleStateImageBehavior = false;
            this.playListView.View = System.Windows.Forms.View.Details;
            // 
            // titleColumnHeader
            // 
            this.titleColumnHeader.Text = "Title";
            this.titleColumnHeader.Width = 150;
            // 
            // authorColumnHeader
            // 
            this.authorColumnHeader.Text = "Author";
            this.authorColumnHeader.Width = 150;
            // 
            // tableLayoutPanel4
            // 
            this.tableLayoutPanel4.ColumnCount = 2;
            this.tableLayoutPanel4.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel4.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel4.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 20F));
            this.tableLayoutPanel4.Controls.Add(this.plsButton, 0, 0);
            this.tableLayoutPanel4.Controls.Add(this.m3uButton, 1, 0);
            this.tableLayoutPanel4.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel4.Location = new System.Drawing.Point(0, 117);
            this.tableLayoutPanel4.Margin = new System.Windows.Forms.Padding(0);
            this.tableLayoutPanel4.Name = "tableLayoutPanel4";
            this.tableLayoutPanel4.RowCount = 1;
            this.tableLayoutPanel4.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tableLayoutPanel4.Size = new System.Drawing.Size(318, 35);
            this.tableLayoutPanel4.TabIndex = 2;
            // 
            // plsButton
            // 
            this.plsButton.Dock = System.Windows.Forms.DockStyle.Fill;
            this.plsButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.plsButton.Image = ((System.Drawing.Image)(resources.GetObject("plsButton.Image")));
            this.plsButton.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.plsButton.Location = new System.Drawing.Point(1, 1);
            this.plsButton.Margin = new System.Windows.Forms.Padding(1);
            this.plsButton.Name = "plsButton";
            this.plsButton.Size = new System.Drawing.Size(157, 33);
            this.plsButton.TabIndex = 0;
            this.plsButton.Text = "Save &PLS";
            this.plsButton.UseVisualStyleBackColor = true;
            this.plsButton.Click += new System.EventHandler(this.OnPlsButtonClick);
            // 
            // m3uButton
            // 
            this.m3uButton.Dock = System.Windows.Forms.DockStyle.Fill;
            this.m3uButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.m3uButton.Image = ((System.Drawing.Image)(resources.GetObject("m3uButton.Image")));
            this.m3uButton.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.m3uButton.Location = new System.Drawing.Point(160, 1);
            this.m3uButton.Margin = new System.Windows.Forms.Padding(1);
            this.m3uButton.Name = "m3uButton";
            this.m3uButton.Size = new System.Drawing.Size(157, 33);
            this.m3uButton.TabIndex = 2;
            this.m3uButton.Text = "Save &M3U";
            this.m3uButton.UseVisualStyleBackColor = true;
            this.m3uButton.Click += new System.EventHandler(this.OnM3uButtonClick);
            // 
            // tableLayoutPanel5
            // 
            this.tableLayoutPanel5.ColumnCount = 2;
            this.tableLayoutPanel5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel5.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel5.Controls.Add(this.videoRadioButton, 0, 0);
            this.tableLayoutPanel5.Controls.Add(this.audioRadioButton, 1, 0);
            this.tableLayoutPanel5.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tableLayoutPanel5.Location = new System.Drawing.Point(0, 0);
            this.tableLayoutPanel5.Margin = new System.Windows.Forms.Padding(0);
            this.tableLayoutPanel5.Name = "tableLayoutPanel5";
            this.tableLayoutPanel5.RowCount = 1;
            this.tableLayoutPanel5.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tableLayoutPanel5.Size = new System.Drawing.Size(318, 25);
            this.tableLayoutPanel5.TabIndex = 5;
            // 
            // videoRadioButton
            // 
            this.videoRadioButton.Checked = true;
            this.videoRadioButton.Dock = System.Windows.Forms.DockStyle.Fill;
            this.videoRadioButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.videoRadioButton.Image = ((System.Drawing.Image)(resources.GetObject("videoRadioButton.Image")));
            this.videoRadioButton.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.videoRadioButton.Location = new System.Drawing.Point(3, 1);
            this.videoRadioButton.Margin = new System.Windows.Forms.Padding(3, 1, 3, 1);
            this.videoRadioButton.Name = "videoRadioButton";
            this.videoRadioButton.Size = new System.Drawing.Size(153, 23);
            this.videoRadioButton.TabIndex = 0;
            this.videoRadioButton.TabStop = true;
            this.videoRadioButton.Text = "Generate Video";
            this.videoRadioButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.videoRadioButton.UseVisualStyleBackColor = true;
            this.videoRadioButton.CheckedChanged += new System.EventHandler(this.OnVideoRadioButtonCheckedChanged);
            // 
            // audioRadioButton
            // 
            this.audioRadioButton.Dock = System.Windows.Forms.DockStyle.Fill;
            this.audioRadioButton.Image = ((System.Drawing.Image)(resources.GetObject("audioRadioButton.Image")));
            this.audioRadioButton.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.audioRadioButton.Location = new System.Drawing.Point(162, 1);
            this.audioRadioButton.Margin = new System.Windows.Forms.Padding(3, 1, 3, 1);
            this.audioRadioButton.Name = "audioRadioButton";
            this.audioRadioButton.Size = new System.Drawing.Size(153, 23);
            this.audioRadioButton.TabIndex = 1;
            this.audioRadioButton.Text = "Generate Audio";
            this.audioRadioButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.audioRadioButton.UseVisualStyleBackColor = true;
            this.audioRadioButton.CheckedChanged += new System.EventHandler(this.OnAudioRadioButtonCheckedChanged);
            // 
            // YouTubeMultiPlaylistAggregatorForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(324, 362);
            this.Controls.Add(this.tableLayoutPanel1);
            this.Controls.Add(this.mainMenuStrip);
            this.Controls.Add(this.mainStatusStrip);
            this.Name = "YouTubeMultiPlaylistAggregatorForm";
            this.Text = "YouTube MultiPlaylist Aggregator";
            this.mainMenuStrip.ResumeLayout(false);
            this.mainMenuStrip.PerformLayout();
            this.mainStatusStrip.ResumeLayout(false);
            this.mainStatusStrip.PerformLayout();
            this.tableLayoutPanel1.ResumeLayout(false);
            this.tableLayoutPanel2.ResumeLayout(false);
            this.tableLayoutPanel2.PerformLayout();
            this.tableLayoutPanel3.ResumeLayout(false);
            this.tableLayoutPanel4.ResumeLayout(false);
            this.tableLayoutPanel5.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        private System.Windows.Forms.Button m3uButton;
        private System.Windows.Forms.Button plsButton;
        private System.Windows.Forms.RadioButton audioRadioButton;
        private System.Windows.Forms.RadioButton videoRadioButton;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel5;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel4;
        private System.Windows.Forms.ColumnHeader authorColumnHeader;
        private System.Windows.Forms.ColumnHeader titleColumnHeader;
        private System.Windows.Forms.ListView playListView;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel3;
        private System.Windows.Forms.Button shuffledButton;
        private System.Windows.Forms.Button sequentialButton;
        private System.Windows.Forms.Button alternatingButton;
        private System.Windows.Forms.TextBox listTextBox;
        private System.Windows.Forms.Label addLabel;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel2;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel1;
        private System.Windows.Forms.ToolStripStatusLabel statusToolStripStatusLabel;
        private System.Windows.Forms.ToolStripProgressBar progressToolStripProgressBar;
        private System.Windows.Forms.StatusStrip mainStatusStrip;
        private System.Windows.Forms.ToolStripMenuItem aboutToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem helpToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem customValueToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem videosToolStripMenuItem5;
        private System.Windows.Forms.ToolStripMenuItem videosToolStripMenuItem4;
        private System.Windows.Forms.ToolStripMenuItem videosToolStripMenuItem3;
        private System.Windows.Forms.ToolStripMenuItem videosToolStripMenuItem2;
        private System.Windows.Forms.ToolStripMenuItem videosToolStripMenuItem1;
        private System.Windows.Forms.ToolStripMenuItem videosToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem fetchAllToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem addedlistsToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem alternatelastToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem alternatefirstToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem addedVideosToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem optionsToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem selectAllToolStripMenuItem;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator4;
        private System.Windows.Forms.ToolStripMenuItem pasteToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem copyToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem cutToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem editToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem exitToolStripMenuItem;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator2;
        private System.Windows.Forms.ToolStripMenuItem newToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem fileToolStripMenuItem;
        private System.Windows.Forms.MenuStrip mainMenuStrip;
        private System.Windows.Forms.SaveFileDialog saveFileDialog;
    }
}
